apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-test-app-deployment
  labels:
    app: test-app-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: test-app-pod
  template:
    metadata:
      labels:
        app: test-app-pod
    spec:
      containers:
      - name: mysql-db
        image: mysql:latest
        ports:
          - containerPort: 8080
        env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "yes"
      - name: kube-test-app
        image: akhilspalli/kube_test_app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20