name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - uses: docker/login-action@v2
      name: login to docker hub
      with:
        username: ${{  secrets.Dockerhub_username  }}
        password: ${{  secrets.Dockerhub_PAT  }}
    - uses: docker/build-push-action@v4
      name: push the docker image to dockerhub
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: akhilspalli/cloud_run_trial:latest